esphome:
  name: dps_monitor

external_components:
  - source:
      type: git
      url: https://github.com/khangelov/esphome
      ref: main
      path: components/dps_1200

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

sensor:
  - platform: dps_1200
    update_interval: 10s
    vin:
      name: "VIN"
    vout:
      name: "VOUT"
    iin:
      name: "IIN"
    iout:
      name: "IOUT"
    pin:
      name: "Power In"
    pout:
      name: "Power Out"
    temp:
      name: "Temperature"
    fan:
      name: "Fan Speed"
